import sys
sys.path.insert(0, '/Users/chriskim/google-services')
from googleapiclient.discovery import build
from google_client import _get_credentials

creds = _get_credentials()
docs_svc = build('docs', 'v1', credentials=creds)

DOC1 = '16vNPIof661-X22W9gSmKzt7neB5TkxYa2E9LYVNsQKI'  # Call & Shift Patterns
DOC2 = '1_FmsFlppKNhrHxEZE2LE1OIghwEHBOTzUxRcanLgFks'  # Clinic Template Expansion

def clear_and_write(doc_id, segments):
    """
    segments: list of (text, style, bold_prefix_len)
      style: TITLE | SUBTITLE | HEADING_1 | HEADING_2 | NORMAL_TEXT | BULLET
      bold_prefix_len: chars at start of text to make bold (0 = none)
    """
    doc = docs_svc.documents().get(documentId=doc_id).execute()
    content = doc.get('body', {}).get('content', [])
    end_index = content[-1].get('endIndex', 2) - 1

    requests = []
    if end_index > 1:
        requests.append({'deleteContentRange': {'range': {'startIndex': 1, 'endIndex': end_index}}})

    full_text = ''
    para_ranges = []
    pos = 1
    for text, style, bold_prefix_len in segments:
        t = text + '\n'
        para_ranges.append((pos, pos + len(t), style, bold_prefix_len))
        full_text += t
        pos += len(t)

    requests.append({'insertText': {'location': {'index': 1}, 'text': full_text}})

    for (start, end, style, bold_prefix_len) in para_ranges:
        if style == 'BULLET':
            requests.append({'createParagraphBullets': {
                'range': {'startIndex': start, 'endIndex': end - 1},
                'bulletPreset': 'BULLET_DISC_CIRCLE_SQUARE'
            }})
        elif style != 'NORMAL_TEXT':
            requests.append({'updateParagraphStyle': {
                'range': {'startIndex': start, 'endIndex': end},
                'paragraphStyle': {'namedStyleType': style},
                'fields': 'namedStyleType'
            }})
        if bold_prefix_len > 0:
            requests.append({'updateTextStyle': {
                'range': {'startIndex': start, 'endIndex': start + bold_prefix_len},
                'textStyle': {'bold': True},
                'fields': 'bold'
            }})

    docs_svc.documents().batchUpdate(documentId=doc_id, body={'requests': requests}).execute()
    print(f"Written {len(segments)} segments to {doc_id}")


# \u2014 DOC 1: Call & Shift Patterns \u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014

s1 = [
    ("Call & Shift Patterns \u2014 Amion Next", "TITLE", 0),
    ("MARCH 2026   \u00b7   CHRIS KIM \u2014 AMION SCHEDULING", "SUBTITLE", 0),

    ("OVERVIEW", "HEADING_1", 0),
    ("Call & Shift Patterns brings repeating call schedule logic to Amion Next. Coordinators define a named cadence for a call service row \u2014 Q4 overnight, night float, 7-on/7-off, rotation-scoped, multi-week cycle \u2014 and the schedule generates itself. The feature includes visual indicators on the grid (so coordinators can tell what\u2019s generated vs. manual) and multi-row template patterns (for programs whose call structure spans several service rows).", "NORMAL_TEXT", 0),
    ("Programs migrating from Classic to Next cite missing pattern support as their primary blocker. The June 2026 Intermediate-tier cohort includes programs with structural requirements \u2014 rotation-scoped activation, cascade assignments, rest enforcement, multi-row templates \u2014 that manual entry can\u2019t replicate. Targeted for Q2 2026. Related Jira: AMIONMGR-3293 \u00b7 AMIONMGR-3308 (spike \u2014 gate).", "NORMAL_TEXT", 0),

    ("DEFINITION OF SUCCESS", "HEADING_1", 0),
    ("A coordinator at a call-heavy program can configure their full call schedule using patterns in under 2 hours \u2014 vs. days of manual entry today.", "BULLET", 0),
    ("\u226550% of call assignments for newly migrated Intermediate-tier programs are generated by pattern within 30 days of onboarding.", "BULLET", 0),
    ("At least 3 Intermediate-tier programs (including one with multi-row call structures) complete migration by June 2026.", "BULLET", 0),
    ("Coordinators can tell pattern-generated assignments from manual entries at a glance on the call calendar.", "BULLET", 0),
    ("Engineering confirms at the AMIONMGR-3308 spike that the stored JSON schema is machine-readable and compatible with a future conversational rule entry interface.", "BULLET", 0),

    ("MOBILE IMPACT", "HEADING_1", 0),
    ("Pattern configuration is manager-only and web-only. Residents view the resulting schedule on mobile \u2014 pattern-generated assignments appear identically to manually-entered ones. No mobile-specific changes required.", "NORMAL_TEXT", 0),

    ("WHY IS IT WORTH DOING IT", "HEADING_1", 0),
    ("For call-heavy programs, building the call schedule is the most time-consuming task coordinators face each academic year. A typical IM program with 30 residents and 365 call days requires 1,000+ individual entries per year \u2014 rebuilt from scratch every AY because there\u2019s no way to save a repeating pattern. Chief residents, who turn over annually, recreate the same Q4 structure from memory or spreadsheets handed down from predecessors.", "NORMAL_TEXT", 0),
    ("Amion Classic\u2019s Pattern tool solves this directly. Programs migrating to Next cite its absence as the primary reason they\u2019re stuck. The blocked programs include real structural requirements that can\u2019t be approximated with manual entry: multi-row anonymous templates, rotation-scoped activation, cascade assignments, rest enforcement.", "NORMAL_TEXT", 0),
    ("The data model built here \u2014 named descriptor records with typed settings JSON \u2014 is also the foundation for conversational rule entry. The form UI is temporary scaffolding; an LLM-driven interface can replace it later without reworking the backend.", "NORMAL_TEXT", 0),

    ("WHAT AND HOW", "HEADING_1", 0),
    ("What the feature needs to support \u2014 mapped to real program examples:", "NORMAL_TEXT", 0),
    ("7-on/7-off night float (Arrowhead Regional) \u2192 Alternate-week cadence with full-week on/off blocks", "BULLET", 0),
    ("6 Night Call in a row, Mon\u2013Fri only (Aline Ex 1) \u2192 Consecutive-day streaks with day-of-week filter", "BULLET", 0),
    ("Fri Day Call \u2192 Sat+Sun Day+Night Call (Aline Ex 2) \u2192 Cascade: pattern generates downstream assignments on following days", "BULLET", 0),
    ("2 days off after Swing/Night (Aline Ex 3) \u2192 Rest enforcement: skip generation within N days of a qualifying assignment", "BULLET", 0),
    ("Call only during ICU block (Thomas Jefferson) \u2192 Rotation-scoped activation: pattern reads block assignments for active date ranges", "BULLET", 0),
    ("Q3 overnight call in internal medicine \u2192 Every-3rd-day cadence anchored to rotation start date", "BULLET", 0),
    ("4+1, 4+2+2 X+Y cycles (BCM Pediatrics) \u2192 Multi-week cycle where each week has a different call structure", "BULLET", 0),
    ("Night float handoff visibility (residents) \u2192 Pattern links: visual markers on the grid showing which assignments belong to a pattern", "BULLET", 0),

    ("Pattern definition:", "NORMAL_TEXT", 19),
    ("New STI subtype of ManagerRule (CallShiftPattern). Coordinator defines: name, pattern type, cycle interval, days of week, date range, staff type(s), and call service. Stored as a descriptor; assignments resolved on-demand at render and export, not pre-generated. Pattern types: Q-call (Q2/Q3/Q4), Weekly, Biweekly, Alternate week, Night float, Consecutive-day streak, Rotation-scoped, Multi-week cycle, Custom.", "NORMAL_TEXT", 0),
    ("Settings stored in ResultRuleCondition.settings as typed JSON. Example Q4: {\"pattern_type\": \"q_call\", \"cycle_interval\": 4, \"start_date\": \"2026-07-01\", \"end_date\": \"2027-06-30\", \"selected_days\": [\"Mon\",\"Tue\",\"Wed\",\"Thu\",\"Fri\"], \"serviceable_id\": 456, \"staff_type_ids\": [2]}. Flat, named, enumerable \u2014 LLM-generatable.", "NORMAL_TEXT", 0),

    ("Rest enforcement and cascade:", "NORMAL_TEXT", 29),
    ("SequenceRule subtype handles consecutive-shift logic (\u201cwhoever works Friday also works Sat+Sun\u201d) and rest enforcement (\u201c2 days off required after any Swing call\u201d). Operates per-assignment, not over a date range.", "NORMAL_TEXT", 0),

    ("Pattern links:", "NORMAL_TEXT", 14),
    ("Visual markers on the call calendar showing which assignments are pattern-generated vs. manual. A subtle indicator (e.g., colored bar or \u25c6 icon) with a tooltip: \u201cGenerated by: [Pattern Name] \u00b7 Edit rule.\u201d On a dense call row, this is the difference between a legible schedule and an unreadable one.", "NORMAL_TEXT", 0),

    ("Template patterns:", "NORMAL_TEXT", 18),
    ("Multi-row patterns where the call structure is defined first \u2014 e.g., Wards day \u2192 Wards night \u2192 2 days off \u2192 Wards day again, spanning 4 service rows \u2014 and staff are slotted in later. Used by programs with cross-service call sequences. The spike (AMIONMGR-3308) will confirm whether the existing has_many :result_conditions covers this or a separate STI subtype is needed.", "NORMAL_TEXT", 0),

    ("On-demand resolution vs. generation-at-save:", "NORMAL_TEXT", 45),
    ("Pattern records are descriptors; assignments resolve lazily at render and export. Keeps the model lean, avoids stale data when block assignments change, and keeps the settings JSON directly LLM-generatable. Generation-at-save is simpler but creates two-way sync risk. The spike confirms this choice.", "NORMAL_TEXT", 0),

    ("RELATED UI/UX DESIGNS AND INTERACTIONS", "HEADING_1", 0),
    ("Design audit pending: AMIONMGR-3296 (Tim/Brandon) \u2014 required before frontend work begins.", "BULLET", 0),
    ("Entry point: Settings \u2192 Rules & Templates \u2192 new \u201cCall & Shift Patterns\u201d section. Single-row patterns and template patterns live here.", "BULLET", 0),
    ("Pattern links: subtle visual marker on pattern-generated assignments. Click opens \u201cGenerated by: [Pattern Name] \u00b7 Edit rule.\u201d", "BULLET", 0),
    ("Template patterns: structure defined in the rule form; staff assigned to slots separately.", "BULLET", 0),
    ("Figma designs: TBD pending AMIONMGR-3296 audit.", "BULLET", 0),

    ("EVENT TRACKING STRATEGY", "HEADING_1", 0),
    ("Required before this proposal is used to write a technical proposal.", "NORMAL_TEXT", 0),
    ("pattern_created \u2014 CallShiftPattern saved. Properties: pattern_type, cycle_interval, has_day_filter, is_rotation_scoped, staff_type_id, service_id, date_range_days, schedule_id.", "BULLET", 0),
    ("template_pattern_created \u2014 multi-row template saved. Properties: row_count, service_ids, schedule_id.", "BULLET", 0),
    ("pattern_preview_viewed \u2014 preview panel rendered. Properties: pattern_type, resolved_count.", "BULLET", 0),
    ("pattern_conflict_flagged \u2014 conflict detected at render. Properties: pattern_id, conflict_count.", "BULLET", 0),
    ("pattern_link_clicked \u2014 coordinator clicks a pattern link on the grid. Properties: pattern_id, pattern_type.", "BULLET", 0),
    ("Goal: track % of call assignments generated by pattern vs. manual per schedule, weekly for migrated programs.", "BULLET", 0),

    ("SCOPE / STAKEHOLDERS", "HEADING_1", 0),
    ("Affected users: coordinators and chief residents at Intermediate-tier programs \u2014 call-heavy (IM, Surgery, EM, OB) and multi-row (Arrowhead, Thomas Jefferson, BCM Pediatrics). ~15\u201320 programs in the migration pipeline.", "BULLET", 0),
    ("Internal teams: Engineering (backend + frontend), Product, CS (migration readiness and training), Design (audit + pattern form + grid visual treatment).", "BULLET", 0),
    ("Who weighs in: Engineering lead (confirm generation model and multi-row STI at spike); CS / Aline (validate Classic pattern inventory against the 9 examples above); Design (AMIONMGR-3296 audit).", "BULLET", 0),
    ("Effort estimate: Spike 1 week \u2192 Backend (pattern types + resolution service) 3 weeks \u2192 Frontend (form + pattern links) 2 weeks \u2192 Template patterns 2 weeks \u2192 QA 1 week \u2248 9 weeks.", "BULLET", 0),
    ("Timeline: Spike by end of March; core pattern tool + links by mid-May; template patterns + QA by end of May; GA June 2026.", "BULLET", 0),
    ("Comms: CS trained before any migration using patterns begins. No end-user announcement \u2014 pattern-generated assignments look identical to manual from the resident view.", "BULLET", 0),

    ("METRICS (OPTIONAL)", "HEADING_1", 0),
    ("Primary: % of call assignments generated by pattern vs. manual for migrated programs (target: \u226550% within 30 days).", "BULLET", 0),
    ("Secondary: # of Intermediate-tier programs completing migration by Jun 2026; # of template patterns created per program.", "BULLET", 0),
    ("Guardrail: high conflict flag rate per pattern signals pattern configuration UX needs work.", "BULLET", 0),

    ("OPEN QUESTIONS / FUTURE WORK", "HEADING_1", 0),
    ("Generation model: on-demand confirmed, or does engineering prefer generation-at-save for consistency with ClinicTemplate (ADR-006)? Gate: AMIONMGR-3308 spike.", "BULLET", 0),
    ("Rotation-scoped activation: does the resolver need live block assignments at render time? What happens when blocks aren\u2019t finalized yet?", "BULLET", 0),
    ("Template pattern STI: does has_many :result_conditions cover multi-row structures, or is a separate subtype needed? Engineering to confirm at spike.", "BULLET", 0),
    ("Staff slotting UX: does the coordinator assign staff to template slots on the schedule grid or in the rule form?", "BULLET", 0),
    ("Future \u2014 Conversational rule entry: the form UI is scaffolding. The infrastructure here must support \u201cQ4 overnight call for PGY-2s starting July 1\u201d input without backend rework.", "BULLET", 0),
    ("Future \u2014 CP-SAT Autoscheduler (AMIONMGR-3319): CallShiftPattern and SequenceRule descriptors are direct inputs to the constraint solver. Tracked separately; this is a prerequisite.", "BULLET", 0),

    ("DECISION LOG", "HEADING_1", 0),
    ("Mar 2026 \u2014 In the context of pattern storage, facing a choice between pre-generating rows vs. storing a descriptor, we decided on-demand descriptor resolution to keep the model lean and avoid stale-data risk, accepting added query complexity at render time.", "BULLET", 0),
    ("Mar 2026 \u2014 In the context of new rule subtypes, facing a choice between a new table vs. STI extension, we decided to extend ManagerRule STI for consistency with existing rule types, accepting that the settings JSON schema must be well-documented.", "BULLET", 0),

    ("REVIEWED BY", "HEADING_1", 0),
    ("TBD \u2014 Engineering lead (spike review AMIONMGR-3308 \u2014 generation model, multi-row STI, rotation-scoped activation)", "BULLET", 0),
    ("TBD \u2014 Design (AMIONMGR-3296 audit \u2014 pattern form, grid visual treatment, template pattern staff slotting)", "BULLET", 0),
    ("TBD \u2014 CS / Aline (Classic pattern inventory \u2014 confirm all 9 real-program examples are covered)", "BULLET", 0),

    ("API OVERVIEW", "HEADING_1", 0),
    ("Extends manager_rules#create and #update. CallShiftPattern and SequenceRule subtypes created via single atomic POST with rule + all conditions \u2014 no multi-step submission. Required for LLM compatibility.", "NORMAL_TEXT", 0),
    ("New PatternResolutionService: given a CallShiftPattern + date range \u2192 list of (date, staff_type, service) tuples. Handles all cadence types including rotation-scoped (reads block assignments) and cascade. Powers the preview panel and call calendar render.", "NORMAL_TEXT", 0),
    ("Template patterns: new endpoint or STI subtype \u2014 TBD at spike (AMIONMGR-3308).", "NORMAL_TEXT", 0),

    ("STORIES & SPEC", "HEADING_1", 0),
    ("AMIONMGR-3308 \u2014 [Spike] Confirm generation model, finalize pattern_type enum, validate STI extension, confirm multi-row approach", "BULLET", 0),
    ("AMIONMGR-3293 \u2014 Epic: Call & Shift Patterns", "BULLET", 0),
    ("Stories TBD pending spike completion and design audit (AMIONMGR-3296)", "BULLET", 0),
]


# \u2014 DOC 2: Clinic Template Expansion \u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014\u2014

s2 = [
    ("Clinic Template Expansion \u2014 Amion Next", "TITLE", 0),
    ("MARCH 2026   \u00b7   CHRIS KIM \u2014 AMION SCHEDULING", "SUBTITLE", 0),

    ("OVERVIEW", "HEADING_1", 0),
    ("Two extensions to Amion Next\u2019s existing clinic template rule type:", "NORMAL_TEXT", 62),
    ("4-week block cadence \u2014 for ARMC and X+Y programs that use per-week clinic patterns within a 4-week cycle (e.g., Week 1: Mon+Wed; Week 2: Thu only; Week 3: Mon+Wed; Week 4: no clinic). Not supported in Amion Next today; blocks these programs from migrating.", "BULLET", 0),
    ("Cancel clinic rules \u2014 conditions under which template-generated sessions are automatically suppressed when a resident is on-call, post-call, or on a rotation that precludes clinic (e.g., ICU). Without this, coordinators cancel sessions manually every month.", "BULLET", 0),
    ("No new data model required. Both extensions are schema additions to the existing ClinicTemplate subtype and its ResultRuleCondition.settings JSON. The generation-at-save model (ADR-006) is preserved. Related Jira: AMIONMGR-3292 \u00b7 AMIONMGR-3306.", "NORMAL_TEXT", 0),

    ("DEFINITION OF SUCCESS", "HEADING_1", 0),
    ("All identified ARMC and X+Y programs can configure their 4-week per-week clinic patterns without workarounds and complete migration by Jun 2026.", "BULLET", 0),
    ("Coordinators at call-heavy programs spend \u226420% of current time manually canceling clinic sessions \u2014 cancel rules handle the rest.", "BULLET", 0),
    ("A canceled session is reinstatable in \u22642 clicks and marked as a manual override (auditable).", "BULLET", 0),
    ("CS understands cancel rule behavior (suppress vs. delete; reversibility) before any migration using cancel rules begins.", "BULLET", 0),

    ("MOBILE IMPACT", "HEADING_1", 0),
    ("Clinic template configuration is manager-only and web-only. Residents view the resulting schedule on mobile \u2014 canceled sessions will appear with a distinct visual treatment. No mobile-specific changes required.", "NORMAL_TEXT", 0),

    ("WHY IS IT WORTH DOING IT", "HEADING_1", 0),
    ("The initial ClinicTemplate shipped for Simple-tier programs on weekly or biweekly cadences. ARMC and X+Y programs use per-week variation within a 4-week block cycle \u2014 a structure Classic supports and these programs have relied on for years. Without it in Next, they hit a hard migration blocker.", "NORMAL_TEXT", 0),
    ("Cancel clinic rules address a second high-effort problem. Call-heavy programs (IM, Surgery, EM, OB) must manually cancel every clinic session that conflicts with on-call or ICU assignments. For a 30-resident program with Q4 overnight call and ICU rotations, that\u2019s dozens of manual cancellations per month. Classic\u2019s rule writer has cancel clinic logic coordinators rely on heavily \u2014 without it in Next, these programs carry significant ongoing overhead even after migration.", "NORMAL_TEXT", 0),

    ("WHAT AND HOW", "HEADING_1", 0),
    ("4-Week Block Cadence:", "NORMAL_TEXT", 21),
    ("Extend ResultRuleCondition.settings with frequency: \"every_4_weeks\" and per-week day configuration. No new model. Generates individual session records at apply time, consistent with ADR-006. Example: {\"frequency\": \"every_4_weeks\", \"week_1_days\": [\"Mon\",\"Wed\"], \"week_2_days\": [\"Thu\"], \"week_3_days\": [\"Mon\",\"Wed\"], \"week_4_days\": []}.", "NORMAL_TEXT", 0),

    ("Cancel Clinic Rules:", "NORMAL_TEXT", 20),
    ("Layered on top of templates \u2014 templates generate sessions; cancel rules suppress specific ones. Two levels:", "NORMAL_TEXT", 0),
    ("Simple cancel \u2014 cancel when resident is on-call or post-call. Configurable scope: all staff types or specific training levels. (Classic equivalent: Cancel Clinic checkboxes in schedule Preferences.)", "BULLET", 0),
    ("Advanced cancel \u2014 cancel by block service (ICU rotation), staff type, assignment type (overnight vs. backup), or composite conditions. (Classic equivalent: Rule Writer advanced cancel clinic rules.)", "BULLET", 0),

    ("Key design decisions:", "NORMAL_TEXT", 21),
    ("Cancel rules suppress, don\u2019t delete \u2014 canceled sessions are visually distinct and reinstatable. Manual reinstatement persists until explicitly removed. Stale template bug (AMIONMGR-3223) is out of scope \u2014 tracked separately.", "NORMAL_TEXT", 0),

    ("RELATED UI/UX DESIGNS AND INTERACTIONS", "HEADING_1", 0),
    ("Entry point: Settings \u2192 Rules & Templates \u2192 Clinic Template \u2192 frequency dropdown adds \u201c4-Week Cycle\u201d option.", "BULLET", 0),
    ("4-week cadence form: per-week day selectors (4 rows of checkboxes, or \u201cNo sessions\u201d toggle per week).", "BULLET", 0),
    ("Cancel rules: new \u201c+ Add Cancel Rule\u201d button. Simple vs. advanced mode toggle.", "BULLET", 0),
    ("Canceled session visual treatment: TBD (grayed text, strikethrough, or distinct color chip) \u2014 requires design input.", "BULLET", 0),
    ("Reinstatement flow: click canceled session \u2192 \u201cReinstate\u201d \u2192 marked as override.", "BULLET", 0),
    ("Figma designs: TBD pending design kickoff.", "BULLET", 0),

    ("EVENT TRACKING STRATEGY", "HEADING_1", 0),
    ("Required before this proposal is used to write a technical proposal.", "NORMAL_TEXT", 0),
    ("clinic_template_created \u2014 extend existing event: add frequency (\"weekly\" | \"biweekly\" | \"every_4_weeks\") and week_N_days_count per week.", "BULLET", 0),
    ("cancel_clinic_rule_created \u2014 cancel rule saved. Properties: rule_level (\"simple\" | \"advanced\"), cancel_condition, staff_type_scoped, schedule_id.", "BULLET", 0),
    ("clinic_session_canceled_by_rule \u2014 cancel rule suppresses a session. Properties: rule_id, cancel_condition, session_date, staff_type_id.", "BULLET", 0),
    ("clinic_session_reinstated \u2014 coordinator reinstates a canceled session. Properties: rule_id, days_since_cancellation.", "BULLET", 0),
    ("Goal: measure manual cancellation rate before/after cancel rules enabled for migrated programs.", "BULLET", 0),

    ("SCOPE / STAKEHOLDERS", "HEADING_1", 0),
    ("Affected users: coordinators at ARMC programs, X+Y programs, and call-heavy programs needing cancel clinic. ~10\u201315 programs in the migration pipeline.", "BULLET", 0),
    ("Internal teams: Engineering (backend + frontend), Product, CS (migration readiness, cancel rule training), Design (canceled session visual treatment).", "BULLET", 0),
    ("Who weighs in: Engineering lead (cancel rule evaluation model \u2014 aligns with AMIONMGR-3308 spike); CS (confirm ARMC/X+Y program list); Design (visual treatment for canceled sessions).", "BULLET", 0),
    ("Effort estimate: 4-week cadence backend ~1 week; cancel rules backend ~2 weeks; frontend ~2 weeks \u2248 4\u20135 weeks. Can run parallel to call/shift patterns backend.", "BULLET", 0),
    ("Timeline: Backend by mid-April; frontend by mid-May; QA + migration pilot by end of May; GA June 2026.", "BULLET", 0),
    ("Comms: CS must understand cancel vs. delete distinction and reinstatement flow before any migration using cancel rules begins.", "BULLET", 0),

    ("METRICS (OPTIONAL)", "HEADING_1", 0),
    ("Primary: # of ARMC/X+Y programs completing migration by Jun 2026 (currently blocked).", "BULLET", 0),
    ("Secondary: % reduction in manual clinic session cancellations per month; reinstatement rate.", "BULLET", 0),
    ("Guardrail: reinstatement rate >20% per program per month signals cancel rule configuration UX needs work.", "BULLET", 0),

    ("OPEN QUESTIONS / FUTURE WORK", "HEADING_1", 0),
    ("Cancel rule evaluation model: generation-time (call schedule must be finalized first) or render-time (live, reflects call changes immediately)? Must align with AMIONMGR-3308 spike.", "BULLET", 0),
    ("Visual treatment for canceled sessions: grayed text, strikethrough, or distinct color chip? Needs design decision before frontend starts.", "BULLET", 0),
    ("Re-application flow: when a 4-week template definition changes after initial application, how does the coordinator update already-generated sessions?", "BULLET", 0),
    ("Cancel rule UI placement: part of the clinic template form, or a separate rule category?", "BULLET", 0),
    ("Future \u2014 CP-SAT Autoscheduler (AMIONMGR-3319): ClinicTemplate descriptors (4-week cadence + cancel conditions) are inputs to the future constraint solver. Requires this as a prerequisite.", "BULLET", 0),

    ("DECISION LOG", "HEADING_1", 0),
    ("Mar 2026 \u2014 In the context of 4-week cadence storage, facing a choice between a new ClinicTemplate subtype vs. extending settings JSON, we decided to extend ResultRuleCondition.settings for consistency with ADR-006, accepting that the settings JSON grows in complexity.", "BULLET", 0),
    ("Mar 2026 \u2014 In the context of canceled session behavior, facing a choice between delete (permanent) vs. suppress (reversible), we decided to suppress for reversibility and auditability, accepting the added complexity of tracking override state per session.", "BULLET", 0),

    ("REVIEWED BY", "HEADING_1", 0),
    ("TBD \u2014 Engineering lead (cancel rule evaluation model, aligned with AMIONMGR-3308)", "BULLET", 0),
    ("TBD \u2014 Design (visual treatment for canceled sessions)", "BULLET", 0),

    ("API OVERVIEW", "HEADING_1", 0),
    ("4-week cadence: extends existing clinic template create/update endpoint \u2014 no new endpoint. Template application service updated to recognize every_4_weeks frequency and apply per-week day configuration.", "NORMAL_TEXT", 0),
    ("Cancel rules: new cancel_clinic_rule subtype within ManagerRule STI (TBD at spike). Cancel evaluation service: given session date + staff_member + schedule \u2192 evaluate all cancel rules \u2192 return suppressed/active status.", "NORMAL_TEXT", 0),

    ("STORIES & SPEC", "HEADING_1", 0),
    ("AMIONMGR-3292 \u2014 Epic: Clinic Schedule UX", "BULLET", 0),
    ("AMIONMGR-3306 \u2014 4-week cadence + cancel clinic rules", "BULLET", 0),
    ("Stories TBD pending engineering review of cancel rule evaluation model", "BULLET", 0),
]

clear_and_write(DOC1, s1)
clear_and_write(DOC2, s2)

print(f"\nDOC1 (Call & Shift Patterns): https://docs.google.com/document/d/{DOC1}/edit")
print(f"DOC2 (Clinic Template Expansion): https://docs.google.com/document/d/{DOC2}/edit")
