import sys
sys.path.insert(0, '/Users/chriskim/google-services')
from googleapiclient.discovery import build
from google_client import _get_credentials

creds = _get_credentials()
docs_svc = build('docs', 'v1', credentials=creds)

def clear_and_write(doc_id, segments):
    doc = docs_svc.documents().get(documentId=doc_id).execute()
    content = doc.get('body', {}).get('content', [])
    end_index = content[-1].get('endIndex', 2) - 1

    requests = []
    if end_index > 1:
        requests.append({'deleteContentRange': {'range': {'startIndex': 1, 'endIndex': end_index}}})

    full_text = ''
    para_ranges = []
    pos = 1
    for text, style in segments:
        t = text + '\n'
        para_ranges.append((pos, pos + len(t), style))
        full_text += t
        pos += len(t)

    requests.append({'insertText': {'location': {'index': 1}, 'text': full_text}})

    for (start, end, style) in para_ranges:
        if style == 'BULLET':
            requests.append({'createParagraphBullets': {
                'range': {'startIndex': start, 'endIndex': end - 1},
                'bulletPreset': 'BULLET_DISC_CIRCLE_SQUARE'
            }})
        elif style != 'NORMAL_TEXT':
            requests.append({'updateParagraphStyle': {
                'range': {'startIndex': start, 'endIndex': end},
                'paragraphStyle': {'namedStyleType': style},
                'fields': 'namedStyleType'
            }})

    docs_svc.documents().batchUpdate(documentId=doc_id, body={'requests': requests}).execute()
    print(f"Written {len(segments)} segments to {doc_id}")

DOC1 = '1oRsEcRUWjTN0i7PsJD4ou7GxrBeDAJHCq4w0_gRqIVo'
DOC2 = '1IcPCCLqjnOYFLhynmthcEgcfra0eFRXsbssZnPCz7JA'

s1 = [
    ("Call & Shift Patterns \u2014 Amion Next", "TITLE"),
    ("MARCH 2026   \u00b7   CHRIS KIM \u2014 AMION SCHEDULING", "SUBTITLE"),
    ("OVERVIEW", "HEADING_1"),
    ("We propose adding Call & Shift Patterns to Amion Next: a rule type that lets residency program coordinators define a repeating call or shift structure once \u2014 Q4, night float, 7-on/7-off, alternate week \u2014 and have it populate assignments automatically across the academic year. Today every assignment is entered by hand; there is no repeating-pattern capability in Next. This is the single largest source of scheduling overhead for call-heavy programs and the primary blocker preventing Intermediate-tier programs from migrating. Patterns are targeted for Q2 2026 to meet the June migration deadline. Related Jira: AMIONMGR-3293 (Call & Shift Patterns epic) \u00b7 AMIONMGR-3308 (Patterns spike \u2014 gate).", "NORMAL_TEXT"),
    ("Two new rule subtypes extend the existing ManagerRule STI system \u2014 no new database table required: (1) CallShiftPattern \u2014 a named repeating call structure (Q4, weekly, biweekly, alternate week, night float, 7-on/7-off), stored as a descriptor with assignments resolved on-demand at render/export; (2) SequenceRule \u2014 consecutive-shift logic. This work lays the data model for future conversational rule entry and is prerequisite infrastructure for the CP-SAT autoscheduler (AMIONMGR-3319).", "NORMAL_TEXT"),
    ("DEFINITION OF SUCCESS", "HEADING_1"),
    ("A coordinator can define a Q4, weekly, biweekly, 7-on/7-off, or night float pattern in under 5 minutes with no hand-entry of individual dates.", "BULLET"),
    ("\u226550% of call assignments for newly migrated Intermediate-tier programs are generated by pattern within 30 days of onboarding.", "BULLET"),
    ("At least 3 Intermediate-tier programs complete migration by June 2026 \u2014 currently blocked by the absence of pattern support.", "BULLET"),
    ("Engineering confirms at spike review (AMIONMGR-3308) that the stored JSON schema is machine-readable and compatible with the future conversational rule entry interface.", "BULLET"),
    ("MOBILE IMPACT", "HEADING_1"),
    ("Amion Next is a web-only product. No mobile impact at this time. Pattern-generated assignments will be visible to residents in the Viewer experience on mobile web, displayed identically to manually-entered assignments.", "NORMAL_TEXT"),
    ("WHY IS IT WORTH DOING IT", "HEADING_1"),
    ("For call-heavy programs, building the call schedule is the most time-consuming task coordinators face every academic year. A typical IM program with 30 residents and 365 call days requires 1,000+ individual date entries per year \u2014 all repeated from scratch each AY because there is no way to save a repeating pattern. Chief residents, who turn over annually, rebuild the same Q4 structure from memory or spreadsheets handed down from predecessors.", "NORMAL_TEXT"),
    ("Amion Classic's Pattern tool directly addresses this. Programs migrating from Classic to Next cite the absence of pattern support as the primary reason they cannot complete migration. Without patterns, Intermediate-tier migration cannot proceed \u2014 blocking a significant segment of the June 2026 migration target.", "NORMAL_TEXT"),
    ("Beyond migration: the data model designed here (named descriptor records with enumerable, typed settings JSON) is the permanent investment that makes conversational rule entry possible. The form UI is temporary scaffolding; an LLM-driven interface replaces it when ready.", "NORMAL_TEXT"),
    ("WHAT AND HOW", "HEADING_1"),
    ("CallShiftPattern: A new STI subtype of ManagerRule. The coordinator defines name, pattern type, cycle interval, days of week, date range, staff type(s), and call service. Stored as a descriptor; assignments resolved on-demand at render and export \u2014 not pre-generated rows. Supported pattern types: Q-call (Q2/Q3/Q4), Weekly, Biweekly, Alternate week (7-on/7-off), Night float, Custom. Settings in ResultRuleCondition.settings: {\"pattern_type\": \"q_call\", \"cycle_interval\": 4, \"start_date\": \"2026-07-01\", \"end_date\": \"2027-06-30\", \"selected_days\": [\"Mon\"], \"serviceable_id\": 456, \"staff_type_ids\": [2]}.", "NORMAL_TEXT"),
    ("SequenceRule: Handles N shifts in a row and N days off after shift type. Operates per-assignment. ResultRuleCondition settings: sequence_type (consecutive | days_off_before | days_off_after | conditional_follow), count, day_of_week_restriction, then_service_id with then_offset_days.", "NORMAL_TEXT"),
    ("Minimal Coordinator UI (scaffolding): A form on the Rules & Templates settings page with name, pattern type dropdown, cycle interval, day selector, date range, staff type + service dropdowns, and a server-rendered preview panel showing first 6\u201310 resolved dates. This is temporary scaffolding \u2014 the conversational text input replaces it when ready.", "NORMAL_TEXT"),
    ("Design choice \u2014 on-demand resolution: Patterns are descriptors; assignments resolve lazily. Keeps the model lean, avoids two-way sync problems when block assignments change, and means the stored JSON is directly LLM-generatable. Alternative (generation-at-save) is simpler but creates stale-data risk. The spike (AMIONMGR-3308) confirms this choice.", "NORMAL_TEXT"),
    ("RELATED UI/UX DESIGNS AND INTERACTIONS", "HEADING_1"),
    ("Design audit pending: AMIONMGR-3296 (Tim/Brandon) \u2014 must complete before frontend work begins.", "BULLET"),
    ("Entry point: Settings \u2192 Rules & Templates \u2192 new \u201cCall & Shift Patterns\u201d category with \u201c+ Add\u201d button.", "BULLET"),
    ("On the call calendar, pattern-generated assignments display with a subtle visual marker distinguishing them from manually-entered assignments. Clicking opens \u201cGenerated by: [Pattern Name] \u00b7 Edit rule.\u201d", "BULLET"),
    ("Figma designs: TBD pending design audit completion (AMIONMGR-3296).", "BULLET"),
    ("EVENT TRACKING STRATEGY", "HEADING_1"),
    ("Define event tracking before this proposal serves as the source of a technical proposal. This section is required.", "NORMAL_TEXT"),
    ("pattern_created \u2014 fired when a CallShiftPattern or SequenceRule is saved. Properties: pattern_type, cycle_interval, staff_type_id, service_id, date_range_days, schedule_id.", "BULLET"),
    ("pattern_preview_viewed \u2014 fired when the preview panel renders. Properties: pattern_type, resolved_count.", "BULLET"),
    ("pattern_conflict_flagged \u2014 fired when a conflict is detected at render. Properties: pattern_id, conflict_count, conflict_type.", "BULLET"),
    ("pattern_deactivated / pattern_deleted \u2014 fired on deactivate or delete. Properties: pattern_type, was_active_days.", "BULLET"),
    ("Analytics goal: measure % of call assignments generated by pattern vs. manual entry per schedule, tracked weekly for migrated programs.", "BULLET"),
    ("SCOPE / STAKEHOLDERS", "HEADING_1"),
    ("Affected users: Residency program coordinators and chief residents at Intermediate-tier programs (call-heavy: IM, Surgery, EM, OB). Approx. 15\u201320 programs in the migration pipeline.", "BULLET"),
    ("Internal teams impacted: Engineering (backend + frontend), Product, CS (migration readiness and training), Design (audit + form UI).", "BULLET"),
    ("Who weighs in: Engineering lead (confirm generation model + STI approach at spike); CS (confirm Classic pattern inventory via Aline); Design (AMIONMGR-3296 audit).", "BULLET"),
    ("Effort estimate: Spike 1 week \u2192 Backend 3 weeks \u2192 Frontend 2 weeks = ~6 weeks total. Spike gates all implementation.", "BULLET"),
    ("Timeline: Spike complete by end of March; backend + frontend by mid-May; QA + migration pilot by end of May; GA June 2026.", "BULLET"),
    ("Comms plan: CS trained before any migration using patterns begins. No end-user announcement needed \u2014 patterns are a coordinator tool invisible to Viewers.", "BULLET"),
    ("METRICS (OPTIONAL)", "HEADING_1"),
    ("Primary: % of call assignments generated by pattern vs. manual entry for migrated programs (target: \u226550% within 30 days of onboarding).", "BULLET"),
    ("Secondary: # of Intermediate-tier programs completing migration by Jun 2026; time from schedule setup to first published call schedule.", "BULLET"),
    ("Guardrail: Conflict flag rate per pattern \u2014 if high, indicates pattern configuration UX needs improvement.", "BULLET"),
    ("OPEN QUESTIONS / FUTURE WORK", "HEADING_1"),
    ("Generation model: Is on-demand the agreed approach, or does engineering prefer generation-at-save for consistency with ClinicTemplate (ADR-006)? Gate: AMIONMGR-3308 spike.", "BULLET"),
    ("SequenceRule Q2 scope: Is SequenceRule included in Q2 alongside CallShiftPattern, or deferred to Q3?", "BULLET"),
    ("Multiple-THEN architecture: Does has_many :result_conditions cover multi-step sequences? Needs engineering confirmation before backend work starts.", "BULLET"),
    ("Future \u2014 Conversational rule entry: The form UI is scaffolding. Infrastructure built here must support a conversational interface without rework.", "BULLET"),
    ("Future \u2014 CP-SAT Autoscheduler (AMIONMGR-3319): CallShiftPattern and SequenceRule descriptors will be direct inputs to the constraint solver. Tracked separately; requires this as a prerequisite.", "BULLET"),
    ("DECISION LOG", "HEADING_1"),
    ("Mar 2026 \u2014 In the context of call/shift pattern storage, facing a choice between pre-generating assignment rows vs. storing a descriptor, we decided to use on-demand descriptor-only resolution to achieve a lean model that avoids two-way sync problems and supports LLM generatability, accepting added query complexity at render time.", "BULLET"),
    ("Mar 2026 \u2014 In the context of new rule subtypes, facing a choice between a new database table vs. STI extension, we decided to extend ManagerRule STI for consistency with existing rule types, accepting that the settings JSON schema must be well-documented.", "BULLET"),
    ("REVIEWED BY", "HEADING_1"),
    ("TBD \u2014 Engineering lead (spike review, AMIONMGR-3308)", "BULLET"),
    ("TBD \u2014 Design (AMIONMGR-3296 audit)", "BULLET"),
    ("API OVERVIEW", "HEADING_1"),
    ("Extends the existing manager_rules#create and #update endpoints. Both subtypes created via a single atomic POST with rule + all conditions \u2014 no multi-step submission. Required for LLM compatibility. New PatternResolutionService: given a CallShiftPattern + date range \u2192 list of (date, staff_type, service) tuples. Powers the preview panel and call calendar render.", "NORMAL_TEXT"),
    ("STORIES & SPEC", "HEADING_1"),
    ("AMIONMGR-3308 \u2014 [Spike] Confirm generation model, finalize pattern_type enum values, validate STI extension approach", "BULLET"),
    ("AMIONMGR-3293 \u2014 Epic: Call & Shift Patterns", "BULLET"),
    ("Stories TBD pending spike completion and design audit", "BULLET"),
]

s2 = [
    ("Clinic Template Expansion \u2014 Amion Next", "TITLE"),
    ("MARCH 2026   \u00b7   CHRIS KIM \u2014 AMION SCHEDULING", "SUBTITLE"),
    ("OVERVIEW", "HEADING_1"),
    ("We propose two extensions to Amion Next's existing clinic template rule type: (1) 4-week block cadence support, and (2) cancel clinic rules. ARMC and X+Y residency programs use 4-week per-week clinic patterns where the session schedule varies by week within a cycle (e.g., Week 1: Mon+Wed; Week 2: Thu only; Week 3: Mon+Wed; Week 4: no clinic). Call-heavy programs need clinic sessions to automatically cancel when a resident is on-call, post-call, or on a rotation that precludes clinic (e.g., ICU). Neither capability exists in Amion Next today, blocking these programs from migrating. Both extensions target Q2 2026 for the June Intermediate-tier migration deadline. Related Jira: AMIONMGR-3292 \u00b7 AMIONMGR-3306.", "NORMAL_TEXT"),
    ("No new data model is required \u2014 both extensions are schema additions to the existing ClinicTemplate rule subtype and its ResultRuleCondition.settings JSON. The generation-at-save model (ADR-006) is preserved.", "NORMAL_TEXT"),
    ("DEFINITION OF SUCCESS", "HEADING_1"),
    ("All identified ARMC and X+Y programs can configure their 4-week per-week clinic patterns without workarounds, completing migration by Jun 2026.", "BULLET"),
    ("Coordinators at call-heavy programs spend \u226420% of current time manually canceling clinic sessions \u2014 cancel rules automate the rest.", "BULLET"),
    ("A canceled session is reinstatable by a coordinator in \u22642 clicks and is marked as a manual override (auditable).", "BULLET"),
    ("Cancel rule behavior (suppress vs. delete; reversibility) is documented and understood by CS before any migration using cancel rules begins.", "BULLET"),
    ("MOBILE IMPACT", "HEADING_1"),
    ("Amion Next is a web-only product. No mobile impact at this time. Canceled sessions will be visible to residents in the Viewer experience on mobile web with a visual treatment indicating canceled status (exact treatment TBD per open question below).", "NORMAL_TEXT"),
    ("WHY IS IT WORTH DOING IT", "HEADING_1"),
    ("The initial ClinicTemplate shipped for Simple-tier programs using weekly or biweekly cadences. ARMC programs and X+Y rotation models require per-week variation within a 4-week block cycle \u2014 a structure Amion Classic supports and that these programs have been using for years. Without 4-week cadence support, these programs face a hard migration blocker: they cannot recreate their existing clinic schedules in Next.", "NORMAL_TEXT"),
    ("Cancel clinic rules address a second high-effort problem: call-heavy programs (IM, Surgery, EM, OB) must manually cancel every clinic session that conflicts with on-call or ICU assignments. For a 30-resident program with Q4 overnight call and ICU rotations, this is dozens of manual cancellations per month. The Classic rule writer has cancel clinic logic that coordinators rely on heavily \u2014 without it in Next, these programs face significant ongoing overhead even after migration.", "NORMAL_TEXT"),
    ("WHAT AND HOW", "HEADING_1"),
    ("4-Week Block Cadence: Extend ResultRuleCondition.settings to support frequency: \"every_4_weeks\" with per-week day configuration. No new model. Generates individual session records across the AY following the defined per-week pattern, consistent with ADR-006. Example: {\"frequency\": \"every_4_weeks\", \"week_1_days\": [\"Mon\",\"Wed\"], \"week_2_days\": [\"Thu\"], \"week_3_days\": [\"Mon\",\"Wed\"], \"week_4_days\": []}.", "NORMAL_TEXT"),
    ("Cancel Clinic Rules: Layer on top of templates \u2014 templates generate sessions; cancel rules suppress specific ones. Two levels: (1) Simple cancel \u2014 cancel when resident is on-call or post-call, configurable to on-call only or on-call + post-call, scoped to all or specific staff types. (2) Advanced cancel \u2014 cancel by block service (ICU rotation), by staff type, by assignment type (overnight vs. backup), or composite conditions.", "NORMAL_TEXT"),
    ("Key design decisions: Cancel rules suppress, don't delete \u2014 canceled sessions are visually distinct and reinstatable. Manual reinstatement is an override that persists until explicitly removed. Stale template bug (AMIONMGR-3223) is out of scope \u2014 tracked separately.", "NORMAL_TEXT"),
    ("RELATED UI/UX DESIGNS AND INTERACTIONS", "HEADING_1"),
    ("Entry point: Settings \u2192 Rules & Templates \u2192 Clinic Template \u2192 frequency dropdown gains \u201c4-Week Cycle\u201d option.", "BULLET"),
    ("4-week cadence form: per-week day selectors (4 rows of day checkboxes, or \u201cNo sessions\u201d toggle per week).", "BULLET"),
    ("Cancel rules: new \u201c+ Add Cancel Rule\u201d button on the clinic template settings page. Simple vs. advanced mode toggle.", "BULLET"),
    ("Canceled session visual treatment: TBD (grayed text, strikethrough, or distinct color chip) \u2014 open question requiring design input.", "BULLET"),
    ("Reinstatement flow: click canceled session \u2192 \u201cReinstate\u201d \u2192 session marked as override.", "BULLET"),
    ("Figma designs: TBD pending design kickoff.", "BULLET"),
    ("EVENT TRACKING STRATEGY", "HEADING_1"),
    ("Define event tracking before this proposal serves as the source of a technical proposal. This section is required.", "NORMAL_TEXT"),
    ("clinic_template_created \u2014 extend existing event with new property: frequency (\"weekly\" | \"biweekly\" | \"every_4_weeks\"). Properties: frequency, week_N_days_count per week, schedule_id.", "BULLET"),
    ("cancel_clinic_rule_created \u2014 fired when a cancel rule is saved. Properties: rule_level (\"simple\" | \"advanced\"), cancel_condition (\"on_call\" | \"post_call\" | \"block_service\" | \"composite\"), staff_type_scoped (bool), schedule_id.", "BULLET"),
    ("clinic_session_canceled_by_rule \u2014 fired when a cancel rule suppresses a session. Properties: rule_id, cancel_condition, session_date, staff_type_id.", "BULLET"),
    ("clinic_session_reinstated \u2014 fired when a coordinator reinstates a canceled session. Properties: rule_id, days_since_cancellation.", "BULLET"),
    ("Analytics goal: measure manual cancellation rate before/after cancel rules enabled for migrated programs.", "BULLET"),
    ("SCOPE / STAKEHOLDERS", "HEADING_1"),
    ("Affected users: Residency program coordinators at ARMC programs, X+Y programs, and call-heavy programs with cancel clinic needs. Approx. 10\u201315 programs in the migration pipeline.", "BULLET"),
    ("Internal teams impacted: Engineering (backend + frontend), Product, CS (migration readiness, cancel rule training), Design (cancel session visual treatment).", "BULLET"),
    ("Who weighs in: Engineering lead (cancel rule evaluation model \u2014 aligns with AMIONMGR-3308 spike decision); CS (confirm which ARMC/X+Y programs are in scope); Design (visual treatment for canceled sessions).", "BULLET"),
    ("Effort estimate: 4-week cadence backend ~1 week; cancel rules backend ~2 weeks; frontend ~2 weeks = ~4\u20135 weeks total. Can run parallel to call/shift patterns backend.", "BULLET"),
    ("Timeline: Backend by mid-April; frontend by mid-May; QA + migration pilot by end of May; GA June 2026.", "BULLET"),
    ("Comms plan: CS must be trained on the cancel vs. delete distinction and the reinstatement flow before any migration using cancel rules begins.", "BULLET"),
    ("METRICS (OPTIONAL)", "HEADING_1"),
    ("Primary: # of ARMC/X+Y programs completing migration by Jun 2026 (currently blocked).", "BULLET"),
    ("Secondary: % reduction in manual clinic session cancellations per month for programs using cancel rules vs. not; reinstatement rate.", "BULLET"),
    ("Guardrail: Reinstatement rate >20% per program per month = signal that cancel rule configuration UX needs improvement.", "BULLET"),
    ("OPEN QUESTIONS / FUTURE WORK", "HEADING_1"),
    ("Cancel rule evaluation model: Generation-time (call schedule must be finalized first) or render-time (live, reflects call changes immediately)? Must align with AMIONMGR-3308 spike decision.", "BULLET"),
    ("Visual treatment for canceled sessions: Grayed text, strikethrough, or distinct color chip? Needs design decision before frontend work starts.", "BULLET"),
    ("Re-application flow: When a 4-week template definition changes after initial application, what is the coordinator's path to update already-generated sessions?", "BULLET"),
    ("Cancel rule UI placement: Configured as part of the clinic template form, or as a separate rule category?", "BULLET"),
    ("Future \u2014 CP-SAT Autoscheduler (AMIONMGR-3319): ClinicTemplate descriptors (4-week cadence + cancel conditions) are inputs to the future constraint solver. Tracked separately; requires this as a prerequisite.", "BULLET"),
    ("DECISION LOG", "HEADING_1"),
    ("Mar 2026 \u2014 In the context of 4-week cadence storage, facing a choice between a new ClinicTemplate subtype vs. extending the existing settings JSON, we decided to extend ResultRuleCondition.settings to achieve consistency with ADR-006, accepting that the settings JSON grows in complexity.", "BULLET"),
    ("Mar 2026 \u2014 In the context of canceled session behavior, facing a choice between delete (permanent) vs. suppress (reversible), we decided to suppress to achieve reversibility and auditability, accepting the added complexity of tracking override state per session.", "BULLET"),
    ("REVIEWED BY", "HEADING_1"),
    ("TBD \u2014 Engineering lead (cancel rule evaluation model, aligned with AMIONMGR-3308)", "BULLET"),
    ("TBD \u2014 Design (visual treatment for canceled sessions)", "BULLET"),
    ("API OVERVIEW", "HEADING_1"),
    ("4-week cadence: extends existing clinic template create/update endpoint \u2014 no new endpoint. The frequency field and week_N_days fields are added to the ResultRuleCondition settings payload. The template application service must be updated to recognize every_4_weeks frequency and apply per-week day configuration.", "NORMAL_TEXT"),
    ("Cancel rules: new cancel_clinic_rule subtype within ManagerRule STI (or added as condition logic on ClinicTemplate \u2014 TBD at spike). Cancel evaluation service: given a session date + staff_member + schedule \u2192 evaluate all cancel rules \u2192 return suppressed/active status.", "NORMAL_TEXT"),
    ("STORIES & SPEC", "HEADING_1"),
    ("AMIONMGR-3292 \u2014 Epic: Clinic Schedule UX", "BULLET"),
    ("AMIONMGR-3306 \u2014 4-week cadence + cancel clinic rules", "BULLET"),
    ("Stories TBD pending engineering review of cancel rule evaluation model", "BULLET"),
]

clear_and_write(DOC1, s1)
clear_and_write(DOC2, s2)

# Also update the template doc with the blank template structure
TEMPLATE_ID = '1s2bW74ekXuC5R6bFlJl09u1a1XIZmNTeKFfWdM6IX24'
template_segments = [
    ("Product Proposal Title", "TITLE"),
    ("MONTH DD, YYYY   \u00b7   YOUR NAME \u2014 YOUR TEAM NAME", "SUBTITLE"),
    ("OVERVIEW", "HEADING_1"),
    ("Keep this short. This is the opening of your proposal and the only thing most people will ever read. Follow the inverted pyramid: opening sentence(s) should state clearly what you're proposing and why. Include the \"when\" (a quarterly goal, client deadline). State \"who\" is affected. Mention anything novel or controversial. Link to any sources that prompted the proposal.", "NORMAL_TEXT"),
    ("DEFINITION OF SUCCESS", "HEADING_1"),
    ("Concisely and clearly define what success looks like. This section is non-optional.", "NORMAL_TEXT"),
    ("[Success criterion 1]", "BULLET"),
    ("[Success criterion 2]", "BULLET"),
    ("MOBILE IMPACT", "HEADING_1"),
    ("Define how this change impacts mobile teams. For Amion Next (web-only): note that there is no direct mobile impact and describe how the change surfaces on mobile web if applicable.", "NORMAL_TEXT"),
    ("WHY IS IT WORTH DOING IT", "HEADING_1"),
    ("Expand on the \"why.\" Have you identified a problem impacting users? A user need? A business challenge or opportunity? Quantify the opportunity with impact to user growth, engagement, or revenue where possible. If expanding an existing feature, include historical context.", "NORMAL_TEXT"),
    ("WHAT AND HOW", "HEADING_1"),
    ("Expand on the \"what\" and \"how.\" Front-load higher-level descriptions. Give reasons for design choices. Link to or embed product sketches and diagrams. Mention downsides or technical debt. Present alternatives with pros and cons if applicable.", "NORMAL_TEXT"),
    ("RELATED UI/UX DESIGNS AND INTERACTIONS", "HEADING_1"),
    ("Attach or link to any designs related to this feature. List all interactions (where this is navigated from, transitions, etc.).", "NORMAL_TEXT"),
    ("Figma: [link]", "BULLET"),
    ("Entry point: [describe navigation path]", "BULLET"),
    ("Key interactions: [describe]", "BULLET"),
    ("EVENT TRACKING STRATEGY", "HEADING_1"),
    ("Define your event tracking strategy as it pertains to Dox-Analytics and Segment event tracking. This is a CRUCIAL aspect of building a new feature & product and it should be taken into consideration before this proposal serves as the source of a technical proposal. This section is a must have.", "NORMAL_TEXT"),
    ("[event_name] \u2014 fired when [trigger]. Properties: [prop1], [prop2], [schedule_id].", "BULLET"),
    ("[event_name] \u2014 fired when [trigger]. Properties: [prop1], [prop2].", "BULLET"),
    ("SCOPE / STAKEHOLDERS", "HEADING_1"),
    ("Try to answer the following questions. You don't have to answer all of them, only the relevant ones. Typically the most important element will be how you plan to communicate during development and how you will communicate the rollout plan.", "NORMAL_TEXT"),
    ("Affected users: [Who will see or be impacted by this change?]", "BULLET"),
    ("Internal teams impacted: [Engineering, Design, CS, etc.]", "BULLET"),
    ("Who weighs in: [Who should review this proposal?]", "BULLET"),
    ("Effort estimate: [Approximate size \u2014 will be refined in engineering discussions]", "BULLET"),
    ("Timeline: [Target quarter or relative dates]", "BULLET"),
    ("Comms plan: [How will rollout be communicated to internal stakeholders and end users?]", "BULLET"),
    ("METRICS (OPTIONAL)", "HEADING_1"),
    ("Description of what the PM will be measuring to assess success and drive future iterations.", "NORMAL_TEXT"),
    ("Primary metric: [metric]", "BULLET"),
    ("Secondary metrics: [metrics]", "BULLET"),
    ("Guardrail: [metric that signals something is wrong]", "BULLET"),
    ("OPEN QUESTIONS / FUTURE WORK", "HEADING_1"),
    ("List unanswered questions that affect design decisions. Note how you intend to expand on this proposal in the future.", "NORMAL_TEXT"),
    ("[Open question 1]", "BULLET"),
    ("[Open question 2]", "BULLET"),
    ("DECISION LOG", "HEADING_1"),
    ("Document important decisions made along the way. Format: Date \u2014 In the context of [use case], facing [concern], we decided to [decision] to achieve [goal], accepting [downside].", "NORMAL_TEXT"),
    ("[Date] \u2014 [Decision log entry]", "BULLET"),
    ("REVIEWED BY", "HEADING_1"),
    ("[Date] \u2014 [Reviewer name]: [Notes and questions]", "BULLET"),
    ("API OVERVIEW", "HEADING_1"),
    ("Link to an API proposal detailing design decisions, backward compatibility, proposed types, proposed queries/mutations, and security scopes. Are there other teams or products that could benefit from these APIs?", "NORMAL_TEXT"),
    ("API proposal: [link]", "BULLET"),
    ("STORIES & SPEC", "HEADING_1"),
    ("Link to stories this proposal generated. It may be too early \u2014 come back and add links once stories are created in Jira.", "NORMAL_TEXT"),
    ("[Jira epic]: [link]", "BULLET"),
    ("[Story]: [link]", "BULLET"),
]
clear_and_write(TEMPLATE_ID, template_segments)
print("All done.")
